apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: local/grpc-client
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-client
spec:
  selector:
    app: client
  ports:
  - port: 8000